import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={dmSans.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
